# Generated by Django 3.1.6 on 2021-02-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('population', models.IntegerField()),
                ('population_density', models.DecimalField(decimal_places=3, max_digits=5)),
                ('median_age', models.IntegerField()),
                ('aged_65_older', models.DecimalField(decimal_places=3, max_digits=5)),
                ('aged_70_older', models.DecimalField(decimal_places=3, max_digits=5)),
                ('gdp_per_capita', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exteme_poverty', models.DecimalField(blank=True, decimal_places=3, max_digits=5)),
                ('diabetes_prevalence', models.DecimalField(decimal_places=4, max_digits=8)),
                ('female_smokers', models.IntegerField(blank=True)),
                ('male_smokers', models.IntegerField(blank=True)),
                ('handwashing_facilities', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hospital_beds_per_thousand', models.IntegerField()),
                ('life_expectancy', models.DecimalField(decimal_places=3, max_digits=5)),
                ('human_development_index', models.DecimalField(decimal_places=3, max_digits=5)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent', to='covid.continent')),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('icu_patients', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='covid.country')),
            ],
        ),
    ]
