# Generated by Django 3.1.6 on 2021-02-07 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210206_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icu_patients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='new_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CovidData',
        ),
    ]
