# Generated by Django 3.1.6 on 2021-02-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210206_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='exteme_poverty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='female_smokers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='male_smokers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='median_age',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
