# Generated by Django 3.1.6 on 2021-02-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210206_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='countryyy',
        ),
    ]
