# Generated by Django 3.1.6 on 2021-02-07 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210206_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['countryyy'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.continent'),
        ),
    ]
